version: 2
jobs:
  build:
    docker:
      - image: openjdk:8-jdk
    environment:
        GRADLE_OPTS: -Xmx1024m -XX:MaxMetaspaceSize=256m
        GRADLE_USER_HOME: .gradle-home
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-home
      - run: ./gradlew --no-daemon check
      - store_artifacts:
          path: build/reports
      - save_cache:
          key: gradle-home-modules
          paths:
            - .gradle-home